In [1]:
import numpy as np

In [6]:
a=np.array([[1,0],[0,1]])
b=np.array([1,1])
print a.dot(b[:,np.newaxis])

[[1]
 [1]]


In [3]:
a.shape

(2, 2)

In [4]:
b.shape

(2,)

In [7]:
a=np.array([[1,2,3],[2,5,6],[6,7,4]])
print 'Matrix:\n',a

Matrix:
[[1 2 3]
 [2 5 6]
 [6 7 4]]


In [9]:
print np.eye(2,3)

[[1. 0. 0.]
 [0. 1. 0.]]


In [11]:
print np.zeros((2,3))

[[0. 0. 0.]
 [0. 0. 0.]]


In [12]:
print np.ones((2,2))

[[1. 1.]
 [1. 1.]]


In [13]:
a=np.arange(0,24,2)
print a

[ 0  2  4  6  8 10 12 14 16 18 20 22]


In [16]:
a=a.reshape((len(a)/3,len(a)/4))

In [17]:
print a

[[ 0  2  4]
 [ 6  8 10]
 [12 14 16]
 [18 20 22]]


In [18]:
print a[1,1]

8


In [19]:
print a[0,:-1]

[0 2]


In [20]:
print a[3,:-2]

[18]


In [21]:
print a[2,2:]

[16]


In [24]:
a[[1,0],[2,2]]

array([10,  4])

In [27]:
a=np.array([1,2,3])
b=np.array([[1],[2],[3]])
print a.shape
print b.shape

(3,)
(3, 1)


In [28]:
print a.T
print b.T

[1 2 3]
[[1 2 3]]


In [29]:
b.shape

(3, 1)

In [30]:
a=np.array([1,2])
b=np.array([2,2])
print a.dot(b)

6


In [32]:
a=np.array([[1,0],[0,1]])
b=np.array([[4,1],[2,2]])
r1=a.dot(b)
r2=np.dot(a,b)
print r1
print r2

[[4 1]
 [2 2]]
[[4 1]
 [2 2]]


In [34]:
c=np.array([1,2])
print b.dot(c)

[6 6]


In [36]:
print a*b

[[4 0]
 [0 2]]


In [37]:
a=np.array([[1,2],[3,4]])
print a.T
print np.transpose(a)

[[1 3]
 [2 4]]
[[1 3]
 [2 4]]


In [38]:
a=np.array([[1,2,1],[1,1,4],[2,3,6]],dtype=np.float32)
print np.linalg.det(a)

-1.0


In [39]:
a=np.array([[1,1,2],[0,1,2]])
print np.linalg.matrix_rank(a)

2


In [45]:
a=np.array([1,2,3])
b=np.array([1,1,1])
c=np.array([2,3,5])
d=np.array([a,b,c])
print d.shape
print np.linalg.matrix_rank(d)==d.shape[0]

(3, 3)
True


In [47]:
a=np.array([[3,1],[1,2]])
b=np.array([9,8])
x=np.linalg.solve(a,b)
print x.dtype

float64


In [48]:
x.dot(a)

array([9., 8.])

In [50]:
a=np.array([[0,1],[1,1],[2,1],[3,1]])
b=np.array([-1,0.2,0.9,2.1])
x,res,r,s=np.linalg.lstsq(a,b)
print x

[ 1.   -0.95]


/home/kor/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:3: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  This is separate from the ipykernel package so we can avoid doing imports until


In [54]:
a=np.array([[1,2,1],[1,1,4],[2,3,6]],dtype=np.float32)
print np.linalg.inv(a)

[[ 6.  9. -7.]
 [-2. -4.  3.]
 [-1. -1.  1.]]


In [55]:
print a.dot(np.linalg.inv(a))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [57]:
print np.linalg.eig(a)

(array([ 8.345132  ,  0.21422778, -0.5593595 ], dtype=float32), array([[-0.24707341, -0.9428197 ,  0.774807  ],
       [-0.4891597 ,  0.280078  , -0.6300621 ],
       [-0.83646727,  0.18068555,  0.05192159]], dtype=float32))


In [58]:
a=5+12j
c=2-1j
print a*c


(22+19j)
