In [1]:
import numpy as np

In [4]:
a=np.array([1,2,3,4])
print 'Vector:\n',a
print type(a)

Vector:
[1 2 3 4]
<type 'numpy.ndarray'>


In [3]:
b=np.arange(1,10)
print type(b)

<type 'numpy.ndarray'>


In [8]:
c=np.array([1,2,3,4],dtype=float)
print 'Float vector\n',c

Float vector
[1. 2. 3. 4.]


In [9]:
d=np.array([True,False,True],dtype=bool)
print 'Bool vector:\n',d

Bool vector:
[ True False  True]


In [10]:
d.dtype

dtype('bool')

In [11]:
e=np.arange(4,8,1)
print 'Vector of number from 4 to 8 by step 2:\n',e

Vector of number from 4 to 8 by step 2:
[4 5 6 7]


In [14]:
k=np.arange(1,10,0.1,dtype=float)
print k.dtype

float64


In [15]:
print d.ndim

1


In [16]:
print k.ndim

1


In [17]:
print k.shape

(90,)


In [18]:
a=np.array([1,2,3])
b=np.array([6,5,4])
k=2
print a,b,k

[1 2 3] [6 5 4] 2


In [19]:
print 'summa',a+b

summa [7 7 7]


In [20]:
print 'raznost',a-b

raznost [-5 -3 -1]


In [21]:
print "mult",a*b

mult [ 6 10 12]


In [22]:
print 'k*a',k*a

k*a [2 4 6]


In [23]:
from numpy.linalg import norm

In [24]:
print norm(a)

3.7416573867739413


In [25]:
print norm(a,ord=1)

6.0


In [26]:
print norm(a,ord=2)

3.7416573867739413


In [27]:
print 'Metric', norm(a-b,ord=2)

Metric 5.916079783099616


In [28]:
from scipy.spatial.distance import cdist

In [29]:
a=np.array([6,3,-5])
b=np.array([-1,0,7])
print 'a',a
print 'razmernost a',a.shape
print 'b',b
print 'razmernost b',b.shape

a [ 6  3 -5]
razmernost a (3,)
b [-1  0  7]
razmernost b (3,)


In [30]:
a=a.reshape((1,3))
print a

[[ 6  3 -5]]


In [31]:
b=b.reshape((3,1))

In [32]:
print b

[[-1]
 [ 0]
 [ 7]]


In [33]:
b=b.reshape((1,3))

In [34]:
print b

[[-1  0  7]]


In [35]:
b.shape

(1, 3)

In [37]:
cdist(a,b,metric='cityblock').shape

(1, 1)

In [38]:
b[np.newaxis,:]

array([[[-1,  0,  7]]])

In [39]:
b.shape

(1, 3)

In [40]:
b[np.newaxis,:].shape

(1, 1, 3)

In [41]:
d=np.array([3,0,8,9,-10])
d.shape

(5,)

In [43]:
d[np.newaxis,:].shape

(1, 5)

In [45]:
d[:,np.newaxis].shape

(5, 1)

In [46]:
a=np.array([6,3,-5])
b=np.array([-1,0,7])
print 'Euclid metric', cdist(a[np.newaxis,:],b[np.newaxis,:],metric='euclidean')

Euclid metric [[14.2126704]]


In [50]:
a=np.array([[1,2],[3,4]])
print a.dtype
print a
print a.shape


int64
[[1 2]
 [3 4]]
(2, 2)


In [51]:
b=np.array([[3,3],[1,5]])
print b.shape

(2, 2)


In [52]:
a1=np.array([1,2])
b1=np.array([3,3])
print norm(a1-b1,ord=2)

2.23606797749979


In [53]:
cdist(a,b,metric='euclidean')

array([[2.23606798, 3.        ],
       [1.        , 2.23606798]])

In [54]:
a=np.array([0,5,-1])
b=np.array([-4,9,3])
print a
print b

[ 0  5 -1]
[-4  9  3]


In [55]:
print 'Scalar a*b',np.dot(a,b)

Scalar a*b 42


In [56]:
print 'Scalar a*b', a.dot(b)

Scalar a*b 42


In [57]:
cos_angle=np.dot(a,b)/norm(a)/norm(b)

In [58]:
print cos_angle

0.8000362836474323
